version: "3.7"
services:
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  polynote:
    image: polynote
    container_name: polynote
    volumes:
      - ./data:/data
    build:
      context: ./polynote
      dockerfile: ./polynote/Dockerfile
    depends_on:
      - spark-master
    ports:
      - "8192:8192"
    environment:
      - SPARK_MASTER_HOST=spark://spark-master
  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-2
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"